# -*- mode: ruby -*-
# vi: set ft=ruby :

 
Vagrant.configure("2") do |config|
  # 2 is the version.
  config.vm.box = "hashicorp/bionic64"
  
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
  
  config.vm.synced_folder "/home/ishi/satswala-mono" , "/home/vagrant/satswala-mono", mount_options: ["dmode=775,fmode=777"]
  config.vm.synced_folder "/media/ishi/Artifacts/.bitcoin" , "/home/vagrant/.bitcoin", mount_options: ["uid=1700"]
  config.vm.synced_folder "/home/ishi/go" , "/home/vagrant/go", mount_options: ["dmode=775,fmode=777"]

  config.vm.network "forwarded_port", guest: "2323", host: "2323", host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: "5000", host: "5000", host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2800"
  end
  
  config.vm.provision "file", source: "basics.bash" ,destination:"/home/vagrant/"
  config.vm.provision "file", source: "aliases.bashrc" ,destination:"/home/vagrant/"
  config.vm.provision "shell", path: "init.bash", run: "once", privileged: true
  
  config.vm.provision "docker"
  config.vm.provision "docker_compose"

  config.vm.provision "shell", inline: <<-SHELL
    usermod -aG docker vagrant
  SHELL

end
