- hosts: swala-m
  gather_facts: false
  vars: 
    home_folder: /home/ishi
  tasks:
    - authorized_key:
        user: sushi
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '{{ home_folder }}/.ssh/swala-m.pub')}}"

    - lineinfile: dest=/etc/ssh/sshd_config regexp='^#?AuthenticationMethods' line='AuthenticationMethods publickey'
    - lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line='PermitRootLogin No'      
    - lineinfile: dest=/etc/ssh/sshd_config regexp='^#Port' line='Port 22909'      
  
    - file: 
        path: /home/sushi
        state: directory
        owner: sushi
        mode: u+rwx,g-rwx,o-rwx
        recurse: yes

    - service:
        name: sshd
        state: reloaded
      # remove /root/.ssh/authorized_keys
