- hosts: swala-v
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Mount s5secrets block storage volume
      shell: |
        mkdir -p /mnt/s5secrets
        mount -o discard,defaults /dev/disk/by-id/scsi-0DO_Volume_s5secrets /mnt/s5secrets
        echo /dev/disk/by-id/scsi-0DO_Volume_s5secrets /mnt/s5secrets ext4 defaults,nofail,discard 0 0 | sudo tee -a /etc/fstab
    - file: 
        path: /mnt/s5secrets/vault/logs
        state: directory
        owner: vault
        mode: 0700
        recurse: yes
    - file: 
        path: /mnt/s5secrets/vault/config
        state: directory
        owner: vault
        mode: 0700
        recurse: yes
    - file: 
        path: /mnt/s5secrets/vault/raft
        state: directory
        owner: vault
        mode: 0700
        recurse: yes

    - file: 
        path: /mnt/s5secrets/certs/dhparam
        state: directory
        owner: nginx
        mode: u+rw,g-rwx,o-rwx
        recurse: yes
        
    - shell:  |
        openssl dhparam -out /mnt/s5secrets/certs/dhparam/dhparam-2048.pem 2048

    - file: 
        path: /mnt/s5secrets/certs/dhparam/
        state: directory
        owner: nginx
        mode: u+rw,g-rwx,o-rwx
        recurse: yes
        