- hosts: swala-v
  gather_facts: false
  vars:
    password: $6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1

  tasks:
    - user: name=nginx password={{ password }}
    - user: name=vault password={{ password }}
    - user: name=entry password={{ password }}    
    - user: name=sushi password={{ password }}    
